# Check on http://lint.travis-ci.org/ after modifying it!
language: python
python:
  - "3.4"
  - "3.5"
os:
  - linux
#  - osx
install:
  - pip install .
script:
  - WITH_COVERAGE=TRUE make all
after_success:
  - coveralls
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/730436c08fd7f89462b0
    on_success: change
    on_failure: always
